-- 회원 인증, 익명 게시판 감사 정보, 공구 소유권, 그라운드 룰 DB 통합

create table if not exists public.members (
  id bigint generated by default as identity primary key,
  student_id integer unique,
  name text not null check (char_length(name) between 1 and 40),
  username text not null,
  login_id text not null unique check (login_id = lower(login_id)),
  class_name text not null,
  role text not null default 'member' check (role in ('member', 'admin')),
  auth_user_id uuid unique references auth.users(id) on delete set null,
  auth_email text unique,
  is_active boolean not null default true,
  must_change_password boolean not null default true,
  password_changed_at timestamptz,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists members_auth_user_id_idx on public.members (auth_user_id);
create index if not exists members_role_active_idx on public.members (role, is_active);
create index if not exists members_class_name_idx on public.members (class_name);

insert into public.members (student_id, name, username, login_id, class_name, role, must_change_password)
values
  (1, '강혜진', '@blueishsun24', 'blueishsun24', '광주_2반', 'member', true),
  (2, '구소현', '@so1454', 'so1454', '광주_2반', 'member', true),
  (3, '김병관', '@s202202923', 's202202923', '광주_2반', 'member', true),
  (4, '김병욱', '@byumguk2', 'byumguk2', '광주_2반', 'member', true),
  (5, '김수정', '@ksujng2338', 'ksujng2338', '광주_2반', 'member', true),
  (6, '김승찬', '@ksc4383', 'ksc4383', '광주_2반', 'member', true),
  (7, '김예빈', '@kyb0617', 'kyb0617', '광주_2반', 'member', true),
  (8, '김정훈', '@kjh5647jh', 'kjh5647jh', '광주_2반', 'member', true),
  (9, '김종민', '@whdals3171', 'whdals3171', '광주_2반', 'member', true),
  (10, '김지명', '@wlaud131', 'wlaud131', '광주_2반', 'member', true),
  (11, '문경준', '@m86865', 'm86865', '광주_2반', 'member', true),
  (12, '박민희', '@gmlakdckdrh', 'gmlakdckdrh', '광주_2반', 'member', true),
  (13, '박세진', '@tpwls06010', 'tpwls06010', '광주_2반', 'member', true),
  (14, '이예빈', '@eee912', 'eee912', '광주_2반', 'member', true),
  (15, '이재훈', '@5613ljh', '5613ljh', '광주_2반', 'member', true),
  (16, '이혜령', '@zzangu1206', 'zzangu1206', '광주_2반', 'member', true),
  (17, '임진석', '@seogi523', 'seogi523', '광주_2반', 'member', true),
  (18, '전준혁', '@jys6041', 'jys6041', '광주_2반', 'member', true),
  (19, '정용철', '@jyc686397', 'jyc686397', '광주_2반', 'member', true),
  (20, '조민정', '@iop11232', 'iop11232', '광주_2반', 'member', true),
  (1001, '김동민', '@dodoking99', 'dodoking99', '광주_1반', 'member', true),
  (1002, '김수현', '@k_sh4770', 'k_sh4770', '광주_1반', 'member', true),
  (4001, '안준영', '@dev.jun0321', 'dev.jun0321', '광주_4반', 'member', true),
  (null, 'G2 관리자', '@g2admin', 'g2admin', '관리자', 'admin', false)
on conflict (login_id) do update set
  student_id = excluded.student_id,
  name = excluded.name,
  username = excluded.username,
  class_name = excluded.class_name,
  role = excluded.role,
  updated_at = now();

create table if not exists public.anonymous_post_authors (
  post_id text primary key references public.anonymous_posts(id) on delete cascade,
  auth_user_id uuid not null references auth.users(id) on delete restrict,
  member_id bigint not null references public.members(id) on delete restrict,
  created_at timestamptz not null default now()
);

create index if not exists anonymous_post_authors_auth_user_id_idx
  on public.anonymous_post_authors (auth_user_id);
create index if not exists anonymous_post_authors_member_id_idx
  on public.anonymous_post_authors (member_id);

alter table public.coffee_orders
  add column if not exists created_by uuid references auth.users(id) on delete set null,
  add column if not exists created_by_member_id bigint references public.members(id) on delete set null,
  add column if not exists creator_name text;

alter table public.coffee_order_items
  add column if not exists participant_user_id uuid references auth.users(id) on delete set null,
  add column if not exists participant_member_id bigint references public.members(id) on delete set null,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create index if not exists coffee_orders_created_by_idx on public.coffee_orders (created_by);
create unique index if not exists coffee_orders_one_active_idx
  on public.coffee_orders (is_active) where is_active;
create index if not exists coffee_order_items_order_id_idx on public.coffee_order_items (order_id);
create index if not exists coffee_order_items_participant_user_id_idx
  on public.coffee_order_items (participant_user_id);

create table if not exists public.ground_rules (
  id text primary key,
  content text not null check (char_length(content) between 1 and 300),
  author_name text not null,
  category text not null default 'etc' check (category in ('time', 'life', 'care', 'social', 'facility', 'etc')),
  seed_likes integer not null default 0 check (seed_likes >= 0),
  is_pinned boolean not null default false,
  tags text[] not null default '{}',
  created_by uuid references auth.users(id) on delete set null,
  created_by_member_id bigint references public.members(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ground_rule_likes (
  rule_id text not null references public.ground_rules(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  member_id bigint references public.members(id) on delete set null,
  created_at timestamptz not null default now(),
  primary key (rule_id, user_id)
);

create index if not exists ground_rules_created_by_idx on public.ground_rules (created_by);
create index if not exists ground_rules_created_at_idx on public.ground_rules (created_at desc);
create index if not exists ground_rule_likes_user_id_idx on public.ground_rule_likes (user_id);

insert into public.ground_rules
  (id, content, author_name, category, seed_likes, is_pinned, tags, created_at, updated_at)
values
  ('gr-1', '입퇴실 체크 잊지 않기', '광주 2반', 'time', 18, true, '{}', '2025-01-06T09:00:00Z', '2025-01-06T09:00:00Z'),
  ('gr-2', '시간 잘 지키기', '광주 2반', 'time', 20, true, '{}', '2025-01-06T09:01:00Z', '2025-01-06T09:01:00Z'),
  ('gr-3', 'SSAFY 물품 잘 다루기', '광주 2반', 'facility', 15, false, '{}', '2025-01-06T09:02:00Z', '2025-01-06T09:02:00Z'),
  ('gr-4', '짝꿍이 졸 때 깨워주기', '광주 2반', 'care', 21, false, array['#졸음주의'], '2025-01-06T09:03:00Z', '2025-01-06T09:03:00Z'),
  ('gr-5', '퇴실할 때 물건 잘 챙기기', '광주 2반', 'life', 14, false, '{}', '2025-01-06T09:04:00Z', '2025-01-06T09:04:00Z'),
  ('gr-6', '담배 냄새 가능한 한 빼고 오기', '광주 2반', 'care', 16, false, '{}', '2025-01-06T09:05:00Z', '2025-01-06T09:05:00Z'),
  ('gr-7', '월 1회 회식하기', '광주 2반', 'social', 19, false, array['#친목'], '2025-01-06T09:06:00Z', '2025-01-06T09:06:00Z'),
  ('gr-8', '서먹서먹하지 않게 함께 한 끼 하기', '광주 2반', 'social', 21, false, array['#친해지길', '#바람'], '2025-01-06T09:07:00Z', '2025-01-06T09:07:00Z')
on conflict (id) do nothing;

create or replace function public.set_community_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists members_set_updated_at on public.members;
create trigger members_set_updated_at
before update on public.members
for each row execute function public.set_community_updated_at();

drop trigger if exists coffee_order_items_set_updated_at on public.coffee_order_items;
create trigger coffee_order_items_set_updated_at
before update on public.coffee_order_items
for each row execute function public.set_community_updated_at();

drop trigger if exists ground_rules_set_updated_at on public.ground_rules;
create trigger ground_rules_set_updated_at
before update on public.ground_rules
for each row execute function public.set_community_updated_at();

create or replace function public.create_anonymous_post(p_title text, p_content text)
returns public.anonymous_posts
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_member_id bigint;
  v_post public.anonymous_posts;
begin
  if v_user_id is null then
    raise exception 'authentication required';
  end if;

  select id into v_member_id
  from public.members
  where auth_user_id = v_user_id and is_active = true;

  if v_member_id is null then
    raise exception 'active member required';
  end if;
  if char_length(trim(p_title)) < 1 or char_length(trim(p_title)) > 80 then
    raise exception 'title must be between 1 and 80 characters';
  end if;
  if char_length(trim(p_content)) < 1 or char_length(trim(p_content)) > 1000 then
    raise exception 'content must be between 1 and 1000 characters';
  end if;

  insert into public.anonymous_posts (id, title, content, created_at, updated_at)
  values ('post-' || replace(gen_random_uuid()::text, '-', ''), trim(p_title), trim(p_content), now(), now())
  returning * into v_post;

  insert into public.anonymous_post_authors (post_id, auth_user_id, member_id)
  values (v_post.id, v_user_id, v_member_id);

  return v_post;
end;
$$;

revoke all on function public.create_anonymous_post(text, text) from public, anon;
grant execute on function public.create_anonymous_post(text, text) to authenticated;

-- 기존의 광범위한 정책을 제거한 뒤 최소 권한 정책으로 교체합니다.
do $$
declare
  p record;
begin
  for p in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename in (
        'members', 'anonymous_posts', 'anonymous_post_authors',
        'coffee_orders', 'coffee_order_items', 'ground_rules', 'ground_rule_likes'
      )
  loop
    execute format('drop policy %I on %I.%I', p.policyname, p.schemaname, p.tablename);
  end loop;
end;
$$;

alter table public.members enable row level security;
alter table public.anonymous_posts enable row level security;
alter table public.anonymous_post_authors enable row level security;
alter table public.coffee_orders enable row level security;
alter table public.coffee_order_items enable row level security;
alter table public.ground_rules enable row level security;
alter table public.ground_rule_likes enable row level security;

create policy members_select_self on public.members
for select to authenticated
using ((select auth.uid()) = auth_user_id);

create policy anonymous_posts_select_members on public.anonymous_posts
for select to authenticated
using (exists (
  select 1 from public.members m
  where m.auth_user_id = (select auth.uid()) and m.is_active = true
));

create policy coffee_orders_select_members on public.coffee_orders
for select to authenticated
using (exists (
  select 1 from public.members m
  where m.auth_user_id = (select auth.uid()) and m.is_active = true
));
create policy coffee_orders_insert_self on public.coffee_orders
for insert to authenticated
with check (
  created_by = (select auth.uid())
  and exists (
    select 1 from public.members m
    where m.auth_user_id = (select auth.uid()) and m.is_active = true
  )
);
create policy coffee_orders_update_owner_admin on public.coffee_orders
for update to authenticated
using (
  created_by = (select auth.uid())
  or exists (
    select 1 from public.members m
    where m.auth_user_id = (select auth.uid()) and m.role = 'admin' and m.is_active = true
  )
)
with check (
  created_by = (select auth.uid())
  or exists (
    select 1 from public.members m
    where m.auth_user_id = (select auth.uid()) and m.role = 'admin' and m.is_active = true
  )
);
create policy coffee_orders_delete_owner_admin on public.coffee_orders
for delete to authenticated
using (
  created_by = (select auth.uid())
  or exists (
    select 1 from public.members m
    where m.auth_user_id = (select auth.uid()) and m.role = 'admin' and m.is_active = true
  )
);

create policy coffee_items_select_members on public.coffee_order_items
for select to authenticated
using (exists (
  select 1 from public.members m
  where m.auth_user_id = (select auth.uid()) and m.is_active = true
));
create policy coffee_items_insert_self on public.coffee_order_items
for insert to authenticated
with check (
  participant_user_id = (select auth.uid())
  and exists (
    select 1 from public.coffee_orders o
    where o.id = order_id and o.is_active = true
  )
);
create policy coffee_items_update_self_owner_admin on public.coffee_order_items
for update to authenticated
using (
  participant_user_id = (select auth.uid())
  or exists (
    select 1 from public.coffee_orders o where o.id = order_id and o.created_by = (select auth.uid())
  )
  or exists (
    select 1 from public.members m
    where m.auth_user_id = (select auth.uid()) and m.role = 'admin' and m.is_active = true
  )
)
with check (
  participant_user_id = (select auth.uid())
  or exists (
    select 1 from public.coffee_orders o where o.id = order_id and o.created_by = (select auth.uid())
  )
  or exists (
    select 1 from public.members m
    where m.auth_user_id = (select auth.uid()) and m.role = 'admin' and m.is_active = true
  )
);
create policy coffee_items_delete_self_owner_admin on public.coffee_order_items
for delete to authenticated
using (
  participant_user_id = (select auth.uid())
  or exists (
    select 1 from public.coffee_orders o where o.id = order_id and o.created_by = (select auth.uid())
  )
  or exists (
    select 1 from public.members m
    where m.auth_user_id = (select auth.uid()) and m.role = 'admin' and m.is_active = true
  )
);

create policy ground_rules_select_members on public.ground_rules
for select to authenticated
using (exists (
  select 1 from public.members m
  where m.auth_user_id = (select auth.uid()) and m.is_active = true
));
create policy ground_rules_insert_self on public.ground_rules
for insert to authenticated
with check (
  created_by = (select auth.uid())
  and exists (
    select 1 from public.members m
    where m.auth_user_id = (select auth.uid()) and m.is_active = true
  )
);
create policy ground_rules_update_owner_admin on public.ground_rules
for update to authenticated
using (
  created_by = (select auth.uid())
  or exists (
    select 1 from public.members m
    where m.auth_user_id = (select auth.uid()) and m.role = 'admin' and m.is_active = true
  )
)
with check (
  created_by = (select auth.uid())
  or exists (
    select 1 from public.members m
    where m.auth_user_id = (select auth.uid()) and m.role = 'admin' and m.is_active = true
  )
);
create policy ground_rules_delete_owner_admin on public.ground_rules
for delete to authenticated
using (
  created_by = (select auth.uid())
  or exists (
    select 1 from public.members m
    where m.auth_user_id = (select auth.uid()) and m.role = 'admin' and m.is_active = true
  )
);

create policy ground_rule_likes_select_members on public.ground_rule_likes
for select to authenticated
using (exists (
  select 1 from public.members m
  where m.auth_user_id = (select auth.uid()) and m.is_active = true
));
create policy ground_rule_likes_insert_self on public.ground_rule_likes
for insert to authenticated
with check (
  user_id = (select auth.uid())
  and exists (
    select 1 from public.members m
    where m.auth_user_id = (select auth.uid()) and m.is_active = true
  )
);
create policy ground_rule_likes_delete_self on public.ground_rule_likes
for delete to authenticated
using (user_id = (select auth.uid()));

revoke all on table public.members from anon, authenticated;
revoke all on table public.anonymous_posts from anon, authenticated;
revoke all on table public.anonymous_post_authors from anon, authenticated;
revoke all on table public.coffee_orders from anon, authenticated;
revoke all on table public.coffee_order_items from anon, authenticated;
revoke all on table public.ground_rules from anon, authenticated;
revoke all on table public.ground_rule_likes from anon, authenticated;

grant select on table public.members to authenticated;
grant select on table public.anonymous_posts to authenticated;
grant select, insert, update, delete on table public.coffee_orders to authenticated;
grant select, insert, update, delete on table public.coffee_order_items to authenticated;
grant select, insert, update, delete on table public.ground_rules to authenticated;
grant select, insert, delete on table public.ground_rule_likes to authenticated;

